---
# Tasks for handling dotfiles
# It assumes they are located in ~/.dotfiles
# Following and adapting these tips and instructions: https://phelipetls.github.io/posts/introduction-to-ansible/

- name: Ensure stow is installed
  become: true
  ansible.builtin.dnf:
    name:
      - stow
    state: present

- name: Run stow
  become: false
  ansible.builtin.shell: "stow -d ~/.dotfiles --dotfiles --verbose=2 ."
  register: result
  changed_when: "result.stderr is search('LINK: ')"
