---
- name: Install overall packages with dnf
  become: true
  ansible.builtin.dnf:
    name:
      - ansible
      - celluloid
      - gimp
      - gnome-tweaks
      - gnucash
      - gnuplot
      - keepassxc
      - mpv
      - neovim
      - pandoc
      - pdfarranger
      - texlive-scheme-full
      - transmission
      - xpad
      - zathura
      - zathura-pdf-poppler
    state: present

- name: Install packages with flatpak
  become: false
  community.general.flatpak:
    name:
      - com.dropbox.Client
      - md.obsidian.Obsidian
      - org.jabref.jabref
    state: present

- name: Install MS fonts
  become: true
  ansible.builtin.dnf:
    name:
      - curl
      - cabextract
      - xorg-x11-font-utils
      - fontconfig
      - https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm
    state: present
