---
- name: My fedora config
  hosts: localhost
  roles:
    - dotfiles      # Install and run stow
    - packages      # Install overall packages with dnf and flatpak
    - msfonts       # MS fonts from mscorefonts2
    # atalhos
    # docker
    # vscode


- name: Install rpmfusion repos and packages
  hosts: localhost
  become: true
  gather_facts: true
  roles:
    - robertdebock.rpmfusion    # Install rpmfusion repos
    # - nvidia                    # Install nvidia drivers
    # - multimedia
